### PR TITLE
Compatibility with Makie 0.17

### PR DESCRIPTION
**Pull request by asinghvi17**
Fixes a small error which caused some graphs to be unusable.  I ran into this when trying to use OSMMakie.

### CODE REVIEW

**Comment by hexaeder** [comment]
this breaks every test with arrows in plots. weird... what happend there?

**Comment by asinghvi17** [comment]
Huh...just ran this locally, I have no idea what is going on - it seems like the marker size might have blown up or something.

**Comment by SimonDanisch** [comment]
Weird indeed.. I thought it's maybe an old Makie version, but the tests seem to use 0.16.6.
And it seems like the size defaults to the scatter theme size, which I suppose should be in pixels?

**Comment by hexaeder** [comment]
I am wondering how `Pixel` ended up there in the first place. Was this a valid option before the markerspace update https://github.com/JuliaPlots/Makie.jl/pull/1596? Also the docs mention `Makie.spaces()` for valid options but this functions does not seem to exist anymore.

**Comment by SimonDanisch** [comment]
Huh, maybe actually the changes that introduced `spaces` and deprecated `Pixel` may not even be tagged yet, when I think about it.

**Comment by hexaeder** [comment]
Makie@0.17 seems to change the glyph placement, I've updated the reference images. Documentation won't run because it can't find some lib used in Jump... not sure what to do there

**Comment by asinghvi17** [comment]
Looks like some JLLs didn't compile - Cbc_jll and Cgl_jll.   This caused upstream libraries to fail.

**Pull request merged**
